---

- name: Clone geoip-api-c repository
  git:
    repo: "{{geoip_repository}}"
    dest: "{{geoip_dest}}"
    version: "{{geoip_branch}}"
  register: _geoip_code

- name: Build geoip-api-c
  shell: >
    ./bootstrap && ./configure {{geoip_configure_opts|default('')}} && make
  args:
    chdir: "{{geoip_dest}}"
  register: _geoip_build
  when: (_geoip_code is changed) or (geoip_force_build)

- name: Install GeoIP
  command: >
    make install
  args:
    chdir: "{{geoip_dest}}"
  become: true
  when: (_geoip_build is success) or (geoip_force_build)

- name: GeoIP libs Symlink
  file:
    src: "{{geoip_lib_prefix|default('/usr/local/lib')}}/{{item}}"
    dest: "{{geoip_lib_dir}}/{{item}}"
    state: link
  with_items:
    - libGeoIP.so
    - libGeoIP.so.1

- name: GeoIP LD update
  command: >
    ldconfig
  when: _geoip_build is success

# vi:ts=2:sw=2:et:ft=yaml
